<a href="https://colab.research.google.com/github/TarunS-2003/numpy_tutorial_notebook/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Installation and import

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

#numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin =0)

#Creating numpy arrays

In [ ]:
#Array creation

arr = np.array([1,2,3,4,5,6]) #A tuple or any array-like object can also be passed
print(arr)
print(type(arr))

[[1 2 3 4 5 6]]
<class 'numpy.ndarray'>


***Dimensions***

In [ ]:
#A dimension specifies level of array depth

#1-D array

arr_1d = np.array( [ 1,2,3,4 ] )

arr_2d = np.array( [ [ 1,2,3,4 ] , [ 5,6,7,8 ] ] )

arr_3d = np.array( [
    [
        [1,2,3] , [4,5,6]
    ],
    [
        [7,8,9] , [10,11,12]
    ]
] )

#ndim provides the dimension of a numpy array

print("The dimension of arr_3d is:",arr_3d.ndim,"\n")

#Creating multi-dimension array

arr_md = np.array([1,2,3,4,5],ndmin = 5)
print(arr_md)

The dimension of arr_3d is: 3 

[[[[[1 2 3 4 5]]]]]


#Accessing array elements

In [ ]:
#An array element can be accessed by it's index number

#Accessing in 1-D array

print("The third element of arr_1d is ",arr_1d[2],"\n")

#Accessing in 2-D array

print("Row 2, Column 3 value of arr_2d is ",arr_2d[1,2],"\n")

#Accessing in 3-D array

print("The third element of the second array of the first array is ",arr_3d[0,1,2])

The third element of arr_1d is  3 

Row 2, Column 3 value of arr_2d is  7 

The third element of the second array of the first array is  6


***Negative Indexing***

In [ ]:
#Negative indexing is used to access the array from the end

print("The last element of  the second array of arr_2d is ",arr_2d[1,-1])

The last element of  the second array of arr_2d is  8


#Slicing

In [ ]:
#Syntax: [start,stop,step]
#Default values: start - 0, stop - length of array - 1, step - 1

print(arr_1d[1:2],"\n")

#Like indexing, slicing also includes negative values

print(arr_1d[-3:-1],"\n")   #stop = -1 - 1 => -2, thus only values at index -3 and -2

#Using step value

print(arr_1d[0::2],"\n")

[2] 

[2 3] 

[1 3] 



In [ ]:
#Slicing in 2-D array

print(arr_2d[1,1:3])

[6 7]


#Data Types

In [ ]:
#dtype attribute is used to check the data type of an array

arr_string = np.array(['python','c++','go'])
print(arr_string.dtype)

<U6


In [ ]:
#Defining the data type at creation

arr_int = np.array([1.1,2.3,3.4], dtype = 'i4')
print(arr_int,"\n")

#Converting an existing array to a differnt data type

arr_int = arr_int.astype(str)
print(arr_int)

[1 2 3] 

['1' '2' '3']


#Copy and View

In [ ]:
#Copy creates a replica of the array and the changes made to it doesn't affect the original

arr = np.array([1,2,3,4,5])
arr_copy = arr.copy()
arr_view = arr.view()

arr_copy[0] = 10
print(arr)

[1 2 3 4 5]
[20  2  3  4  5]
None


In [ ]:
#View refers to the original array and changes to a view affect the original and vice versa

arr_view[0] = 20
print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
#To check if the array owns the data, use "base" attribute

print(arr_copy.base)

None


#Shape and Reshape

In [ ]:
#Shape tells the number of elements in each dimension

arr = np.array([[1,2,3] , [4,5,6]])
print(arr.shape)

(2, 3) 



In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('\nShape of array :', arr.shape)

[[[[[1 2 3 4]]]]]

Shape of array : (1, 1, 1, 1, 4)


***Reshaping***

In [ ]:
#Reshaping from 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Reshaping from 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#This causes an error as we require a total of 3x3 = 9 elements for the expected reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: ignored

In [ ]:
#We can have atmost one unknown dimension

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Flattening a multi-dimensional array to 1-D array

arr.reshape(-1)
print(arr)

[1 2 3 4 5 6 7 8]


#Iterating an array

In [ ]:
#For any dimension array, general python for loop iterated over 1-D components

arr = np.array([[1,2,3],[4,5,6]])
for i in arr:
  print(i)

[1 2 3]
[4 5 6]


In [ ]:
#nditer can be used to iterate over scalar values
arr = np.array([[1, 2, 3],[4, 5, 6]])

for i in np.nditer(arr, flags=['buffered'], op_dtypes=['S']): #op_dtypes - change the data type during iteration; flags = ['buffered'] - provide a space for data type conversion
  print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


In [ ]:
for i in np.nditer(arr[:,::2]):
  print(i)

1
3
4
6


In [ ]:
#ndenumerate is used to mention the sequence numbering / index value

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


#Join

In [ ]:
#concatenate() method of numpy can be used to join two arrays

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
#Joining 2-D arrays

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Using stack() method

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#Stacking along rows

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
#Stacking along columns

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Stacking along height / depth

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


#Split

In [ ]:
#Split is the opposite of join

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
print(newarr.ndmin) # Because return type is list of arrays

[array([1, 2]), array([3, 4]), array([5, 6])]


AttributeError: ignored

In [ ]:
#Unequal split

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
#We also have the method split() available but it will not adjust the elements when elements are less in
#source array for splitting like in example above, array_split() worked properly but split() would fail.

'\nWe also have the method split() available but it will not adjust the elements when elements are less in \nsource array for splitting like in example above, array_split() worked properly but split() would fail.'

In [ ]:
#Using hsplit

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr)

newarr = np.hsplit(arr, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


#Search

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x) # Returns tuple of index where 4 is present

(array([3, 5, 6]),)


***searchsorted()***

In [ ]:
#This method returns the index where the input value should be placed so as to maintain sorted order

arr = np.array([6, 8, 7, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [ ]:
#Search from right side

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [ ]:
#Check for the right indices of multiple values

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


#Sort

In [ ]:
#Return type: copy

arr = np.array([9,8,7,6])
arr = np.sort(arr)

print(arr)

[6 7 8 9]


In [ ]:
#Sorting a 2-D array

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


#Filter

In [ ]:
#Filtering is the process of selecting particular elements from an array and creating a new array with them.
#It is done using boolean index list, where the elements of the list correspond to the elements of array at the exact index.
#True means select the value at that index in array and vice versa.

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = []

for element in arr:
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [ ]:
#A more concise approach


arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
